apiVersion: v1
kind: PersistentVolumeClaim # PVC for Linkding data
metadata:
  name: linkding-data-pvc # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce # Access mode
  resources:
    requests:
      storage: 1Gi # Storage size

---
apiVersion: apps/v1
kind: Deployment # Deployment for Linkding
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.44.1 
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data # Volume mount for Linkding data
              mountPath: /etc/linkding/data # Mount path for Linkding data
      volumes:
        - name: linkding-data # Volume for Linkding data
          persistentVolumeClaim:
            claimName: linkding-data-pvc # Reference to the PVC